"""empty message

Revision ID: dede3605914a
Revises: bb1bdd35b967
Create Date: 2022-09-10 14:16:09.775669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dede3605914a'
down_revision = 'bb1bdd35b967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'oauth_account', ['id'])
    op.create_unique_constraint(None, 'passwords', ['id'])
    op.create_unique_constraint(None, 'roles', ['id'])
    op.create_unique_constraint(None, 'user_sessions', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_sessions', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'passwords', type_='unique')
    op.drop_constraint(None, 'oauth_account', type_='unique')
    # ### end Alembic commands ###
